name = "finews"
main = "src/index.ts"
compatibility_date = "2026-05-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "finews"
database_id = "475f3d97-f340-4ebc-80da-ca9b00042b77"
migrations_dir = "src/db/migrations"

[vars]
ENVIRONMENT = "development"
